from typing import Protocol
from app.domain.models.task import Task


class TaskRepository(Protocol):
    def get_all(self) -> list[Task]: ...
    def get_by_id(self, task_id:str) -> Task | None: ...
    def add(self, task: Task) -> None: ...
    def update(self, task: Task) -> None: ...
    def delete(self, task_id: str) -> None: ...
